src/Entity/Geo/Sala.php
<?php

namespace App\Entity\Geo;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SalaRepository")
 */
class Sala
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     * @var string
     */
    private $nombre;

    /**
     * @ORM\Column(type="string")
     * @var string
     */
    private $direccion;

    /**
     * @ORM\Column(type="string")
     * @var string
     */
    private $localidad;

    /**
     * @ORM\Column(type="string")
     * @var string
     */
    private $mapa_url;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Geo\Provincia")
     * @var Provincia
     */
    private $provincia;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $aforo;


    public function getId(): int
    {
        return $this->id;
    }

    public function getNombre(): string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDireccion(): string
    {
        return $this->direccion;
    }

    public function setDireccion(string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    public function getLocalidad(): string
    {
        return $this->localidad;
    }

    public function setLocalidad(string $localidad): self
    {
        $this->localidad = $localidad;

        return $this;
    }

    public function getMapaUrl(): string
    {
        return $this->mapa_url;
    }

    public function setMapaUrl(string $mapa_url): self
    {
        $this->mapa_url = $mapa_url;

        return $this;
    }

    public function getProvincia(): Provincia
    {
        return $this->provincia;
    }

    public function setProvincia(Provincia $provincia): self
    {
        $this->provincia = $provincia;

        return $this;
    }

    public function getAforo(): ?int
    {
        return $this->aforo;
    }

    public function setAforo(?int $aforo): self
    {
        $this->aforo = $aforo;

        return $this;
    }
}

src/Controller/Gestor/CursoController.php
<?php

namespace App\Controller\Gestor;

use App\Entity\Curso\Curso;
use App\Repository\CursoRepository;
use App\Repository\InscripcionRepository;
use App\Repository\PersonaRepository;
use App\Repository\SalaRepository;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/gestor/curso")
 */
class CursoController extends Controller
{
    /**
     * @var CursoRepository
     */
    protected $repository;


    function __construct(CursoRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/listar", name="gestor_curso_listar")
     * @Route("/", name="gestor_curso_listar_1")
     */
    public function listar()
    {
        $cursos = $this->repository->findAll();

        return $this->render('gestor/curso/listar.html.twig', [
            'cursos' => $cursos,
        ]);
    }

    /**
     * @Route("/mostrar/{id}", requirements={"id": "\d+"}, name="gestor_curso_mostrar")
     * @param int $id
     * @param InscripcionRepository $inscripcionRepository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function mostrar(int $id, InscripcionRepository $inscripcionRepository)
    {
        $curso = $this->repository->find($id);
        $inscripcionesReales = $inscripcionRepository->findInscripcionesReales($curso);
        $inscripcionesEspera = $inscripcionRepository->findInscripcionesEspera($curso);
        $inscripcionesAnuladas = $inscripcionRepository->findInscripcionesAnuladas($curso);
        return $this->render('gestor/curso/mostrar.html.twig', [
            'curso' => $curso,
            'inscripcionesReales' =>  $inscripcionesReales,
            'inscripcionesEspera' => $inscripcionesEspera,
            'inscripcionesAnuladas' => $inscripcionesAnuladas,
        ]);
    }

    /**
     * @Route("/crear", name="gestor_curso_crear")
     * @param SalaRepository $salaRepository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function crear(SalaRepository $salaRepository)
    {
        $salas = $salaRepository->findAll();
        return $this->render('gestor/curso/crear.html.twig', [
            'salas' => $salas,
        ]);
    }

    /**
     * @Route("/copiar/{id}", requirements={"id": "\d+"}, name="gestor_curso_copiar")
     * @param int $id
     * @param SalaRepository $salaRepository
     * @throws ORMException
     * @throws OptimisticLockException
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function copiar(int $id, SalaRepository $salaRepository)
    {
        $cursoOrigen = $this->repository->find($id);
        $cursoDestino = clone $cursoOrigen;
        $this->repository->save($cursoDestino);
        $salas = $salaRepository->findAll();
        return $this->render('gestor/curso/editar.html.twig', [
            'curso' => $cursoDestino,
            'salas' => $salas,
        ]);
    }

    /**
     * @Route("/editar/{id}", requirements={"id": "\d+"}, name="gestor_curso_editar")
     * @param int $id
     * @param SalaRepository $salaRepository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function editar(int $id, SalaRepository $salaRepository)
    {
        $curso = $this->repository->find($id);
        $salas = $salaRepository->findAll();
        return $this->render('gestor/curso/editar.html.twig', [
            'curso' => $curso,
            'salas' => $salas,
        ]);
    }

    /**
     * @Route("/grabar", name="gestor_curso_grabar")
     * @param Request $request
     * @param SalaRepository $salaRepository
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @throws ORMException
     * @throws OptimisticLockException
     */
    public function grabar(Request $request, SalaRepository $salaRepository)
    {
        if ($id = $request->get('id')) {
            $curso = $this->repository->find($id);
        } else {
            $curso = new Curso();
        }
        $sala = $salaRepository->find($request->get('sala_id'));
        $curso
            ->setCodigo($request->get('codigo'))
            ->setDescripcion($request->get('descripcion'))
            ->setFechas($request->get('fechas'))
            ->setHoras($request->get('horas'))
            ->setModulo($request->get('modulo'))
            ->setNombre($request->get('nombre'))
            ->setPlazas($request->get('plazas'))
            ->setSala($sala)
            ->setTurno($request->get('turno'))
            ->setUrl($request->get('url'))
            ;
        $this->repository->save($curso);

        return $this->redirectToRoute("gestor_curso_listar");
    }

    /**
     * @Route("/borrar/{id}", requirements={"id": "\d+"}, name="gestor_curso_borrar")
     * @param int $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function borrar(int $id)
    {
        $curso = $this->repository->find($id);
        try {
            $this->repository->delete($curso);
        } catch (OptimisticLockException $e) {
        } catch (ORMException $e) {
        }

        return $this->redirectToRoute('gestor_curso_listar');
    }

    /**
     * @Route("/candidatos/{id}", requirements={"id": "\d+"}, name="gestor_curso_candidatos")
     * @param int $id
     * @param PersonaRepository $personaRepository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function candidatos(int $id, PersonaRepository $personaRepository)
    {
        $curso = $this->repository->find($id);
        $candidatos = $personaRepository->findCandidatos($curso);

        return $this->render('gestor/curso/candidatos.html.twig', [
            'curso' => $curso,
            'candidatos' => $candidatos,
        ]);
    }
}

src/Controller/Gestor/DefaultController.php
<?php

namespace App\Controller\Gestor;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * @Route("/gestor")
 */
class DefaultController extends Controller
{
    /**
     * @Route("/", name="gestor_inicio")
     * @Route("/inicio", name="gestor_inicio_1")
     */
    public function index()
    {
        return $this->render('gestor/inicio.html.twig', [
            'controller_name' => 'DefaultController',
        ]);
    }
}

src/Controller/Gestor/HomeController.php
<?php

namespace App\Controller\Gestor;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * @Route("/gestor")
 */
class HomeController extends Controller
{
    /**
     * @Route("/inicio", name="gestor_inicio")
     * @Route("/")
     */
    public function index()
    {
        return $this->render('gestor/persona/index.html.twig', [
            'controller_name' => 'PersonaController',
        ]);
    }
}

src/Controller/Gestor/InscripcionController.php
<?php

namespace App\Controller\Gestor;

use App\Entity\Inscripcion\Inscripcion;
use App\Repository\CursoRepository;
use App\Repository\InscripcionEstadoRepository;
use App\Repository\InscripcionRepository;
use App\Repository\PersonaRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * @Route("/gestor/inscripcion")
 */
class InscripcionController extends Controller
{
    const INSCRIPCION_REAL = 1;
    const INSCRIPCION_ESPERA = 2;
    const INSCRIPCION_ANULADA = 4;

    /**
     * @var InscripcionRepository
     */
    protected $repository;


    function __construct(InscripcionRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/grabar", name="gestor_inscripcion_grabar")
     * @param Request $request
     * @param CursoRepository $cursoRepository
     * @param PersonaRepository $personaRepository
     * @param InscripcionEstadoRepository $estadoRepository
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function grabar(Request $request, CursoRepository $cursoRepository, PersonaRepository $personaRepository,
                           InscripcionEstadoRepository $estadoRepository)
    {
        $curso = $cursoRepository->find($request->get('curso_id'));
        $persona = $personaRepository->find($request->get('persona_id'));
        $estado = $estadoRepository->find($request->get('estado_id'));

        $inscripcion = new Inscripcion();
        $inscripcion
            ->setCurso($curso)
            ->setPersona($persona)
            ->setEstado($estado)
            ->setFechaAlta(new \DateTime())
        ;
        $this->repository->save($inscripcion);

        return $this->redirectToRoute('gestor_curso_mostrar', [
            'id' => $curso->getId(),
        ]);
    }

    /**
     * @Route("/cambiar/{id}/{estado_id}", requirements={"id": "\d+", "estado_id": "\d+"}, name="gestor_inscripcion_cambiar_estado")
     * @param int $id
     * @param InscripcionEstadoRepository $estadoRepository
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function cambiarEstado(int $id, int $estado_id, InscripcionEstadoRepository $estadoRepository)
    {
        $inscripcion = $this->repository->find($id);
        $estado = $estadoRepository->find($estado_id);
        $inscripcion->setEstado($estado);
        $this->repository->save($inscripcion);

        return $this->redirectToRoute('gestor_curso_mostrar', [
            'id' => $inscripcion->getCurso()->getId(),
        ]);
    }
}

src/Controller/Gestor/PersonaController.php
<?php

namespace App\Controller\Gestor;

use App\Entity\Persona\Domicilio;
use App\Entity\Persona\Persona;
use App\Repository\PersonaRepository;
use App\Repository\ProvinciaRepository;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * @Route("/gestor/persona")
 */
class PersonaController extends Controller
{
    /**
     * @var PersonaRepository
     */
    protected $repository;


    function __construct(PersonaRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/listar", name="gestor_persona_listar")
     * @Route("/", name="gestor_persona_listar_1")
     */
    public function listar()
    {
        $personas = $this->repository->findAll();

        return $this->render('gestor/persona/listar.html.twig', [
            'personas' => $personas,
        ]);
    }

    /**
     * @Route("/crear", name="gestor_persona_crear")
     * @param ProvinciaRepository $provinciaRepository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function crear(ProvinciaRepository $provinciaRepository)
    {
        $provincias = $provinciaRepository->findAll();

        return $this->render('gestor/persona/crear.html.twig', [
            'provincias' => $provincias,
        ]);
    }

    /**
     * @Route("/editar/{id}", name="gestor_persona_editar")
     * @param int $id
     * @param ProvinciaRepository $provinciaRepository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function editar(int $id, ProvinciaRepository $provinciaRepository)
    {
        $persona = $this->repository->find($id);
        $provincias = $provinciaRepository->findAll();
        if (!$persona->getDomicilio()) {
            $persona->setDomicilio(new Domicilio());
        }
        return $this->render('gestor/persona/editar.html.twig', [
            'persona' => $persona,
            'provincias' => $provincias,
        ]);
    }

    /**
     * @Route("/grabar", name="gestor_persona_grabar")
     * @param Request $request
     * @param ProvinciaRepository $provinciaRepository
     * @param ValidatorInterface $validator
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws ORMException
     * @throws OptimisticLockException
     */
    public function grabar(Request $request, ProvinciaRepository $provinciaRepository, ValidatorInterface $validator)
    {
        if ($id = $request->get('id')) {
            $persona = $this->repository->find($id);
        } else {
            $persona = new Persona();
        }
        if (!$persona->getDomicilio()) {
            $persona->setDomicilio(new Domicilio());
        }
        if ($provinciaId = $request->get('provincia_id')) {
            $provincia = $provinciaRepository->find($provinciaId);
            $persona->getDomicilio()->setProvincia($provincia);
        }
        $persona->setApellidos($request->get('apellidos'));
        $persona->setNombre($request->get('nombre'));
        $persona->setCorreo($request->get('correo'));
        $persona->setTelefono($request->get('telefono'));
        $persona->getDomicilio()->setCodigoPostal($request->get('codigo_postal'));
        $persona->getDomicilio()->setLocalidad($request->get('localidad'));
        $persona->getDomicilio()->setNumero($request->get('numero'));
        $persona->getDomicilio()->setVia($request->get('via'));


        $errors = $validator->validate($persona);
        if (count($errors) > 0) {
            $errorsString = (string) $errors;

            return new Response($errorsString);
        }

        $this->repository->save($persona);

        return $this->redirectToRoute("gestor_persona_listar");
    }

    /**
     * @Route("/borrar/{id}", requirements={"id": "\d+"}, name="gestor_persona_borrar")
     * @param int $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @throws ORMException
     * @throws OptimisticLockException
     */
    public function borrar(int $id)
    {
        $persona = $this->repository->find($id);
        $this->repository->delete($persona);

        return $this->redirectToRoute('gestor_persona_listar');
    }
}

templates/gestor/sala/crear.html.twig
{% extends 'gestor/layout_dashboard.html.twig' %}
{% set titulo = 'Crear Aula' %}

{% block contenido %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ titulo }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
                <a href="{{ path('gestor_sala_listar') }}" class="btn btn-sm btn-danger"><span
                            data-feather="arrow-left-circle"></span> Cancelar</a>
            </div>
        </div>
    </div>

    <div class="col-md-8 order-md-1">
        <form class="form" action="{{ path('gestor_sala_grabar') }}" method="post">
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input class="form-control" name="nombre" type="text">
            </div>

            <div class="form-group">
                <label for="direccion">Dirección</label>
                <input class="form-control" name="direccion" type="text">
            </div>

            <div class="form-group">
                <label for="provincia_id">Provincia</label>
                <select class="form-control" name="provincia_id">
                    {% for provincia in provincias %}
                        <option value="{{ provincia.id }}">{{ provincia.nombre }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="localidad">Localidad</label>
                <input class="form-control" name="localidad" type="text">
            </div>

            <div class="form-group">
                <label for="mapa_url">URL Mapa</label>
                <input class="form-control" name="mapa_url" type="url">
            </div>

            <div class="form-group">
                <label for="aforo">Aforo</label>
                <input class="form-control" name="aforo" type="number" max="1000" min="0">
            </div>

            <button class="btn btn-primary btn-lg btn-block" type="submit">Grabar Sala</button>

        </form>
    </div>
{% endblock %}

templates/gestor/sala/editar.html.twig
{% extends 'gestor/layout_dashboard.html.twig' %}
{% set titulo = 'Editar ' ~ sala.nombre %}

{% block contenido %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ titulo }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
                <a href="{{ path('gestor_sala_listar') }}" class="btn btn-sm btn-danger"><span
                            data-feather="arrow-left-circle"></span> Cancelar</a>
            </div>
        </div>
    </div>

    <div class="col-md-8 order-md-1">
        <form class="form" action="{{ path('gestor_sala_grabar') }}" method="post">
            <input type="hidden" name="id" value="{{ sala.id }}">
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input class="form-control" name="nombre" type="text" value="{{ sala.nombre }}">
            </div>

            <div class="form-group">
                <label for="direccion">Dirección</label>
                <input class="form-control" name="direccion" type="text" value="{{ sala.direccion }}">
            </div>

            <div class="form-group">
                <label for="provincia_id">Provincia</label>
                <select class="form-control" name="provincia_id">
                    {% for provincia in provincias %}
                        <option value="{{ provincia.id }}"
                                {% if sala.provincia.id == provincia.id %}selected{% endif %}>{{ provincia.nombre }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="localidad">Localidad</label>
                <input class="form-control" name="localidad" type="text" value="{{ sala.localidad }}">
            </div>

            <div class="form-group">
                <label for="mapa_url">URL Mapa</label>
                <input class="form-control" name="mapa_url" type="url" value="{{ sala.mapaUrl }}">
            </div>

            <div class="form-group">
                <label for="aforo">Aforo</label>
                <input class="form-control" name="aforo" type="number" value="{{ sala.aforo }}" max="1000" min="0">
            </div>

            <button class="btn btn-primary btn-lg btn-block" type="submit">Guardar Cambios</button>
        </form>
    </div>
{% endblock %}

templates/gestor/sala/listar.html.twig
{% extends 'gestor/layout_dashboard.html.twig' %}
{% set titulo = 'Listado de Aulas' %}

{% block contenido %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ titulo }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
                <a  href="{{ path('gestor_sala_crear') }}" class="btn btn-sm btn-primary"><span
                                data-feather="plus-circle"></span> Crear Aula</a>
                <a href="" class="btn btn-sm btn-outline-secondary">Export</a>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Provincia</th>
                <th>Mapa</th>
                <th>Aforo</th>
            </tr>
            </thead>
            <tbody>
            {% for sala in salas %}
                <tr>
                    <td><a class="badge badge-primary" href="{{ path('gestor_sala_editar', {'id': sala.id}) }}" >{{ sala.id }}</a></td>
                    <td>{{ sala.nombre }}</td>
                    <td>{{ sala.provincia.nombre }}</td>
                    <td>{% if sala.mapaUrl %}<a href ="{{ sala.mapaUrl }}"><span data-feather="map-pin"></span></a>{% endif %}</td>
                    <td>{{ sala.aforo }}</td>
                    <td><a href="{{ path('gestor_sala_borrar', {'id': sala.id}) }}"><span data-feather="trash"></span></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/gestor/sala/mostrar.html.twig
{% extends 'gestor/layout_dashboard.html.twig' %}
{% set titulo = sala.nombre %}

{% block contenido %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ titulo }}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
                <a href="{{ path('gestor_sala_listar') }}" class="btn btn-sm btn-primary"><span
                            data-feather="arrow-left-circle"></span> Lista de Aulas</a>
            </div>
        </div>
    </div>

    <div class="col-md-8 order-md-1">
        <form class="form">
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input class="form-control" name="nombre" type="text" value="{{ sala.nombre }}" readonly>
            </div>
            <div class="form-group">
                <label for="aforo">Aforo</label>
                <input class="form-control" name="aforo" type="number" value="{{ sala.aforo }}" readonly>
            </div>
            <div class="form-group">
                <label for="direccion">Dirección</label>
                <input class="form-control" name="direccion" type="text" value="{{ sala.direccion }}" readonly>
            </div>
            <div class="form-group">
                <label for="localidad">Localidad</label>
                <input class="form-control" name="localidad" type="text" value="{{ sala.localidad }}" readonly>
            </div>
            <div class="form-group">
                <label for="provincia_id">Provincia</label>
                <input class="form-control" name="provincia" type="text" value="{{ sala.provincia.nombre }}" readonly>
            </div>
            <div class="form-group">
                <label for="mapa_url">URL Mapa</label>
                <input class="form-control" name="mapa_url" type="url" value="{{ sala.mapaUrl }}" readonly>
            </div>
        </form>
    </div>
{% endblock %}